export const LayoutActionTypes = {
    UPDATE_TABLE_POSITION: 'UPDATE_TABLE_POSITION',
    TOGGLE__LAYOUT_MODAL: 'TOGGLE__LAYOUT_MODAL',
    SET_ACTIVE_TABLE: 'SET_ACTIVE_TABLE',
    SET_ACTIVE_POSITION: 'SET_ACTIVE_POSITION',
    UPDATE_TABLE: 'UPDATE_TABLE',
    CREATE_TABLE: 'CREATE_TABLE',
    DELETE_TABLE: 'DELETE_TABLE',
    FETCH_START: 'FETCH_START',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_FAILURE: 'FETCH_FAILURE',
    PERSIST_START: 'PERSIST_START',
    PERSIST_SUCCESS: 'PERSIST_SUCCESS',
    PERSIST_FAILURE: 'PERSIST_FAILURE'
}