export const ReservationActionTypes = {
  TOGGLE_RESERVATION_MODAL: "TOGGLE_RESERVATION_MODAL",
  SET_ACTIVE_TABLE_RESERVATION: "SET_ACTIVE_TABLE_RESERVATION",
  DELETE_RESERVATION: "DELETE_RESERVATION",
  UPSERT_RESERVATION: "UPSERT_RESERVATION"
};
