export const ReservationActionTypes = {
  TOGGLE_RESERVATION_MODAL: "TOGGLE_RESERVATION_MODAL",
  SET_ACTIVE_TABLE_RESERVATION: "SET_ACTIVE_TABLE_RESERVATION",
  DELETE_RESERVATION: "DELETE_RESERVATION",
  UPSERT_RESERVATION: "UPSERT_RESERVATION",
  FETCH_START_RESERVATION: "FETCH_START_RESERVATION",
  FETCH_SUCCESS_RESERVATION: "FETCH_SUCCESS_RESERVATION",
  FETCH_FAILURE_RESERVATION: "FETCH_FAILURE_RESERVATION",
  PERSIST_START_RESERVATION: "PERSIST_START_RESERVATION",
  PERSIST_SUCCESS_RESERVATION: "PERSIST_SUCCESS_RESERVATION",
  PERSIST_FAILURE_RESERVATION: "PERSIST_FAILURE_RESERVATION",
};
